<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller; use App\Models\User; use Illuminate\Http\Request; use Illuminate\Support\Facades\Hash;
class UserManagementController extends Controller {
 public function index(Request $request){$q=User::query()->select('id','name','identifiant','email','role','is_active','created_at')->orderByDesc('id'); if($request->filled('role'))$q->where('role',$request->role); if($request->filled('search')){$s=$request->search;$q->where(fn($x)=>$x->where('name','like',"%$s%")->orWhere('identifiant','like',"%$s%")->orWhere('email','like',"%$s%"));} return response()->json($q->get());}
 public function store(Request $request){$v=$request->validate(['name'=>'required|string|max:255','identifiant'=>'required|string|max:60|unique:users,identifiant','email'=>'required|email|max:255|unique:users,email','role'=>'required|in:admin,agent,candidat','password'=>'required|string|min:8']); $u=User::create(['name'=>$v['name'],'identifiant'=>strtoupper($v['identifiant']),'email'=>$v['email'],'role'=>$v['role'],'password'=>Hash::make($v['password']),'is_active'=>true]); return response()->json(['message'=>'Compte créé avec succès.','user'=>$u],201);}
 public function update(Request $request,User $user){$v=$request->validate(['name'=>'sometimes|string|max:255','email'=>'sometimes|email|max:255|unique:users,email,'.$user->id,'role'=>'sometimes|in:admin,agent,candidat','is_active'=>'sometimes|boolean']);$user->update($v);if(array_key_exists('is_active',$v)&&!$v['is_active'])$user->tokens()->delete();return response()->json(['message'=>'Compte mis à jour.','user'=>$user]);}
 public function resetPassword(Request $request,User $user){$v=$request->validate(['password'=>'required|string|min:8']);$user->update(['password'=>Hash::make($v['password'])]);$user->tokens()->delete();return response()->json(['message'=>'Mot de passe réinitialisé.']);}
 public function destroy(User $user){if($user->id===request()->user()->id)return response()->json(['message'=>'Vous ne pouvez pas supprimer votre propre compte.'],422);$user->tokens()->delete();$user->delete();return response()->json(['message'=>'Compte supprimé.']);}
}
